import { InspectionRecord, OfficerProfile } from '../types';

export const INITIAL_OFFICERS: OfficerProfile[] = [
  {
    id: 'off-101',
    name: 'Insp. Aniket Verma',
    badgeNumber: 'LM-DEL-8942',
    designation: 'Senior Legal Metrology Officer',
    zone: 'Northern Zone - New Delhi Division',
    email: 'aniket.verma@lm.nic.in',
    phone: '+91 98112 34567',
    totalInspections: 142,
    activeStatus: true,
  },
  {
    id: 'off-102',
    name: 'Insp. Rajesh Sharma',
    badgeNumber: 'LM-MUM-4211',
    designation: 'Assistant Controller of Legal Metrology',
    zone: 'Western Zone - Mumbai Central',
    email: 'rajesh.sharma@lm.nic.in',
    phone: '+91 98221 88765',
    totalInspections: 98,
    activeStatus: true,
  },
  {
    id: 'off-103',
    name: 'Insp. Sunita Banerjee',
    badgeNumber: 'LM-KOL-7319',
    designation: 'Legal Metrology Inspector',
    zone: 'Eastern Zone - Kolkata Port & Hub',
    email: 'sunita.b@lm.nic.in',
    phone: '+91 94330 12390',
    totalInspections: 115,
    activeStatus: true,
  },
  {
    id: 'off-104',
    name: 'Insp. K. Ramanathan',
    badgeNumber: 'LM-CHN-5502',
    designation: 'Senior Enforcement Officer',
    zone: 'Southern Zone - Chennai Metro',
    email: 'k.ramanathan@lm.nic.in',
    phone: '+91 98401 54321',
    totalInspections: 84,
    activeStatus: true,
  },
];

export const INITIAL_INSPECTIONS: InspectionRecord[] = [
  {
    id: 'ins-2026-0891',
    memoNumber: 'LM/ENF/2026/0891',
    createdAt: '2026-08-22T08:30:00Z',
    commodityName: 'Himalayan Organic Honey (Pure Raw)',
    category: 'Food & Beverages',
    packageType: 'Glass Jar / Bottle',
    brand: 'NatureFresh Organics',
    manufacturer: 'NatureFresh Agro Foods Ltd.',
    mfgAddress: 'Plot 42, Industrial Area, Solan, Himachal Pradesh - 173212',
    countryOfOrigin: 'India',
    netQuantity: '500 g',
    mrp: '₹ 385.00 (incl. of all taxes)',
    unitSalePrice: '₹ 0.77 / g',
    mfgDate: '06/2026',
    expiryDate: '05/2028',
    batchNumber: 'BATCH-NF-2026/08',
    consumerCare: 'care@naturefreshagro.com | Toll-Free: 1800-266-9900',
    status: 'COMPLIANT',
    score: 96,
    lotSize: 500,
    samplesTested: 20,
    sampleSufficient: true,
    statutorySamplingNote: 'Rule requires testing a sample size of at least 20 packets before generating the legal report.',
    officerName: 'Insp. Aniket Verma',
    officerDesignation: 'Senior Legal Metrology Officer',
    inspectionLocation: 'SuperMart Hypermarket, Connaught Place, New Delhi',
    storeName: 'SuperMart Retail Hub Ltd.',
    storeAddress: 'Shop 14-16, Inner Circle, Connaught Place, New Delhi - 110001',
    declarations: [
      {
        id: 'd-1',
        fieldName: 'Name and Address of Manufacturer',
        ruleReference: 'Rule 6(1)(a)',
        extractedValue: 'NatureFresh Agro Foods Ltd., Plot 42, Solan, HP - 173212',
        status: 'passed',
        confidence: 0.98,
        legalNote: 'Complete postal address with valid PIN code found.',
      },
      {
        id: 'd-2',
        fieldName: 'Generic Commodity Name',
        ruleReference: 'Rule 6(1)(b)',
        extractedValue: 'Pure Raw Himalayan Honey',
        status: 'passed',
        confidence: 0.99,
        legalNote: 'Prominently displayed on Principal Display Panel.',
      },
      {
        id: 'd-3',
        fieldName: 'Net Quantity Declaration',
        ruleReference: 'Rule 6(1)(c)',
        extractedValue: '500 g',
        status: 'passed',
        confidence: 0.97,
        fontHeightMm: 4.5,
        minRequiredFontMm: 4.0,
        legalNote: 'Standard metric symbol "g" used. Font height conforms to Table I (Rule 7).',
      },
      {
        id: 'd-4',
        fieldName: 'Maximum Retail Price (MRP)',
        ruleReference: 'Rule 6(1)(e)',
        extractedValue: '₹ 385.00 (inclusive of all taxes)',
        status: 'passed',
        confidence: 0.98,
        legalNote: 'Mandatory tax inclusivity phrasing present.',
      },
      {
        id: 'd-5',
        fieldName: 'Unit Sale Price (USP)',
        ruleReference: 'Rule 6(11)',
        extractedValue: '₹ 0.77 per g',
        status: 'passed',
        confidence: 0.95,
        legalNote: 'Conforms to 2021/2022 amended PCR mandate for packaging > 200g.',
      },
      {
        id: 'd-6',
        fieldName: 'Consumer Grievance Redressal',
        ruleReference: 'Rule 6(1)(g)',
        extractedValue: 'Executive Contact: Plot 42, Solan | 1800-266-9900 | care@naturefreshagro.com',
        status: 'passed',
        confidence: 0.96,
        legalNote: 'Contains postal address, helpline phone, and email ID.',
      },
    ],
    findings: [
      {
        id: 'f-1',
        ruleNumber: 'Rule 6(1)(a)-(g)',
        ruleTitle: 'Mandatory Statutory Declarations Check',
        severity: 'compliant',
        evidence: 'All 8 mandatory declarations present in accordance with Legal Metrology (Packaged Commodities) Rules, 2011.',
        explanation: 'Package fulfills all font size, layout, unit of measure, and consumer care standards.',
        legalClause: 'Section 36(1) of Legal Metrology Act, 2009',
        penaltySection: 'None (Fully Compliant)',
        recommendedAction: 'No enforcement action necessary. Certified compliant.',
        status: 'passed',
      },
    ],
    images: [
      {
        id: 'img-1',
        previewUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&auto=format&fit=crop&q=80',
        labelType: 'front',
        timestamp: '2026-08-22 08:31 AM',
        source: 'camera',
      },
      {
        id: 'img-2',
        previewUrl: 'https://images.unsplash.com/photo-1587049352851-8d4e89133924?w=800&auto=format&fit=crop&q=80',
        labelType: 'back',
        timestamp: '2026-08-22 08:32 AM',
        source: 'camera',
      },
    ],
    remarks: 'Routine pre-market inspection during market sweep. Package verified compliant.',
    actionTaken: 'Certificate of Compliance Issued',
  },
  {
    id: 'ins-2026-0889',
    memoNumber: 'LM/ENF/2026/0889',
    createdAt: '2026-08-21T14:15:00Z',
    commodityName: 'Imported Lavender Herbal Face Cleanser (250 ml)',
    category: 'Cosmetics & Personal Care',
    packageType: 'Bottle / Pump Dispenser',
    brand: 'GlowSkin Luxury',
    manufacturer: 'BeauTech International Corp., France',
    mfgAddress: 'Paris, France (Importer: Prime Imports Pvt Ltd, Mumbai - 400050)',
    countryOfOrigin: 'Missing on Display Panel',
    netQuantity: '250 ml',
    mrp: '₹ 1,299.00',
    unitSalePrice: 'Missing',
    mfgDate: '01/2026',
    expiryDate: '12/2028',
    batchNumber: 'BATCH-GLOW-X99',
    consumerCare: 'support@primeimports.in',
    status: 'NON_COMPLIANT',
    score: 48,
    lotSize: 1200,
    samplesTested: 50,
    sampleSufficient: true,
    statutorySamplingNote: 'Rule requires testing a sample size of at least 50 packets before generating the legal report.',
    officerName: 'Insp. Rajesh Sharma',
    officerDesignation: 'Assistant Controller of Legal Metrology',
    inspectionLocation: 'Grand Central Mall, Senapati Bapat Marg, Mumbai',
    storeName: 'Aura Luxe Beauty Boutique',
    storeAddress: 'F-22, Level 1, Grand Central Mall, Lower Parel, Mumbai - 400013',
    declarations: [
      {
        id: 'd-10',
        fieldName: 'Country of Origin',
        ruleReference: 'Rule 6(10)',
        extractedValue: 'NOT DECLARED ON PACKAGE',
        status: 'violation',
        confidence: 0.99,
        legalNote: 'Major statutory violation under Rule 6(10) of PCR 2011 for imported commodities.',
      },
      {
        id: 'd-11',
        fieldName: 'Unit Sale Price (USP)',
        ruleReference: 'Rule 6(11)',
        extractedValue: 'NOT PRINTED',
        status: 'violation',
        confidence: 0.97,
        legalNote: 'Missing mandatory USP (₹ per ml) required for packages above standard threshold.',
      },
      {
        id: 'd-12',
        fieldName: 'Maximum Retail Price (MRP)',
        ruleReference: 'Rule 6(1)(e)',
        extractedValue: '₹ 1299.00 (Omitted "incl. of all taxes")',
        status: 'warning',
        confidence: 0.94,
        legalNote: 'Mandatory statutory phrase "inclusive of all taxes" omitted from price tag.',
      },
      {
        id: 'd-13',
        fieldName: 'Consumer Grievance Address',
        ruleReference: 'Rule 6(1)(g)',
        extractedValue: 'Only Email printed (No phone/address)',
        status: 'violation',
        confidence: 0.92,
        legalNote: 'Rule 6(1)(g) requires physical postal address and telephone helpline in addition to email.',
      },
    ],
    findings: [
      {
        id: 'f-10',
        ruleNumber: 'Rule 6(10)',
        ruleTitle: 'Absence of Country of Origin on Imported Package',
        severity: 'major_violation',
        evidence: 'Inspection of imported cosmetic unit revealed complete absence of "Country of Origin" or "Made in [Country]" declaration on the principal display panel or back label.',
        explanation: 'Violation of Rule 6(10) of Legal Metrology (Packaged Commodities) Rules, 2011.',
        legalClause: 'Section 36(1) of Legal Metrology Act, 2009',
        penaltySection: 'Fine of up to ₹25,000 for first offense',
        recommendedAction: 'Issue Statutory Notice under Section 36(1). Compounding notice or seizure of unlabelled stock.',
        status: 'failed',
      },
      {
        id: 'f-11',
        ruleNumber: 'Rule 6(11)',
        ruleTitle: 'Non-Declaration of Unit Sale Price (USP)',
        severity: 'major_violation',
        evidence: 'Package has MRP declared as ₹1299.00 for 250ml volume but does not declare the Unit Sale Price (₹ 5.20 / ml).',
        explanation: 'Mandatory compliance failure as per Ministry of Consumer Affairs Gazette Notification.',
        legalClause: 'Section 36(1) of Legal Metrology Act, 2009',
        penaltySection: 'Compoundable offense or prosecution under Section 36',
        recommendedAction: 'Serve notice to Importer & Retailer to cease sale until compliant stickers applied.',
        status: 'failed',
      },
    ],
    images: [
      {
        id: 'img-3',
        previewUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop&q=80',
        labelType: 'front',
        timestamp: '2026-08-21 02:16 PM',
        source: 'camera',
      },
    ],
    remarks: 'Imported cosmetic stock seized for non-declaration of Country of Origin and USP. Notice dispatched to Importer.',
    actionTaken: 'Statutory Notice Issued & 24 Units Seized under Memo # LM/ENF/2026/0889',
  },
  {
    id: 'ins-2026-0885',
    memoNumber: 'LM/ENF/2026/0885',
    createdAt: '2026-08-20T11:00:00Z',
    commodityName: 'Crispy Roasted Cashews (Salted)',
    category: 'Food & Beverages',
    packageType: 'Foil Pouch / Sachet',
    brand: 'Royal Crunch',
    manufacturer: 'Royal Crunch Confectionery Pvt Ltd',
    mfgAddress: 'GIDC Estate, Phase II, Rajkot, Gujarat - 360003',
    countryOfOrigin: 'India',
    netQuantity: '200 g',
    mrp: '₹ 190.00 (incl. of all taxes)',
    unitSalePrice: '₹ 0.95 / g',
    mfgDate: '07/2026',
    expiryDate: '01/2027',
    batchNumber: 'BATCH-RC-GJ-420',
    consumerCare: 'Customercare: 0281-2445566 | care@royalcrunch.co.in',
    status: 'REVIEW_REQUIRED',
    score: 78,
    lotSize: 850,
    samplesTested: 50,
    sampleSufficient: true,
    statutorySamplingNote: 'Rule requires testing a sample size of at least 50 packets before generating the legal report.',
    officerName: 'Insp. Sunita Banerjee',
    officerDesignation: 'Legal Metrology Inspector',
    inspectionLocation: 'Metro Cash & Carry, Salt Lake Sector V, Kolkata',
    storeName: 'Metro Wholesale Kolkata Hub',
    storeAddress: 'Plot A3, Block EP & GP, Sector V, Salt Lake, Kolkata - 700091',
    declarations: [
      {
        id: 'd-20',
        fieldName: 'Net Quantity Font Height',
        ruleReference: 'Rule 7 & Table I',
        extractedValue: '200 g (Font height measured: 2.2 mm)',
        status: 'warning',
        confidence: 0.88,
        fontHeightMm: 2.2,
        minRequiredFontMm: 4.0,
        legalNote: 'For net quantity 200g-1kg, Table I requires minimum numeral font height of 4.0 mm.',
      },
      {
        id: 'd-21',
        fieldName: 'Unit Symbol Standard',
        ruleReference: 'Rule 6(1)(c)',
        extractedValue: 'Printed as "200 gms" instead of "200 g"',
        status: 'warning',
        confidence: 0.91,
        legalNote: 'Metric unit abbreviation "gms" violates standard symbol "g" under Rule 6(1)(c).',
      },
    ],
    findings: [
      {
        id: 'f-20',
        ruleNumber: 'Rule 7 / Table I',
        ruleTitle: 'Font Height of Net Quantity Below Prescribed Dimension',
        severity: 'minor_violation',
        evidence: 'Numerals of net quantity measure 2.2 mm against statutory requirement of 4.0 mm for 200g net content packages.',
        explanation: 'Minor technical infringement under Rule 7.',
        legalClause: 'Section 36(1) of Legal Metrology Act, 2009',
        penaltySection: 'Advisory Warning / Rectification Notice',
        recommendedAction: 'Issue 15-day Rectification Notice to manufacturer to rectify print cylinder in subsequent batches.',
        status: 'needs_review',
      },
    ],
    images: [
      {
        id: 'img-4',
        previewUrl: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=800&auto=format&fit=crop&q=80',
        labelType: 'front',
        timestamp: '2026-08-20 11:05 AM',
        source: 'upload',
      },
    ],
    remarks: 'Font height marginally below statutory threshold. Manufacturer requested compliance undertaking.',
    actionTaken: '15-Day Rectification Notice Served',
  },
  {
    id: 'ins-2026-0881',
    memoNumber: 'LM/ENF/2026/0881',
    createdAt: '2026-08-19T09:40:00Z',
    commodityName: 'Himalayan Organic Honey (Pure Raw - Squeeze Pack)',
    category: 'Food & Beverages',
    packageType: 'Pouch / Sachet',
    brand: 'NatureFresh Organics',
    manufacturer: 'NatureFresh Agro Foods Ltd.',
    mfgAddress: 'Plot 42, Industrial Area, Solan, Himachal Pradesh - 173212',
    countryOfOrigin: 'India',
    netQuantity: '250 g',
    mrp: '₹ 210.00 (incl. of all taxes)',
    unitSalePrice: '₹ 0.84 / g',
    mfgDate: '06/2026',
    expiryDate: '05/2028',
    batchNumber: 'BATCH-NF-2026/08',
    consumerCare: 'care@naturefreshagro.com | 1800-266-9900',
    status: 'COMPLIANT',
    score: 98,
    lotSize: 500,
    samplesTested: 20,
    sampleSufficient: true,
    statutorySamplingNote: 'Rule requires testing a sample size of at least 20 packets before generating the legal report.',
    officerName: 'Insp. Aniket Verma',
    officerDesignation: 'Senior Legal Metrology Officer',
    inspectionLocation: 'Delhi Duty Free / T3 Airport Terminal, New Delhi',
    storeName: 'Airport Convenience Retail',
    storeAddress: 'T3 Departures, IGI Airport, New Delhi - 110037',
    declarations: [],
    findings: [],
    images: [],
    remarks: 'Batch follow-up inspection at secondary retail store. Full declarations verified.',
    actionTaken: 'Verified Compliant for Batch BATCH-NF-2026/08',
  },
  {
    id: 'ins-2026-0879',
    memoNumber: 'LM/ENF/2026/0879',
    createdAt: '2026-08-18T16:20:00Z',
    commodityName: 'Spicy Masala Cashews (100g)',
    category: 'Food & Beverages',
    packageType: 'Foil Pouch / Sachet',
    brand: 'Royal Crunch',
    manufacturer: 'Royal Crunch Confectionery Pvt Ltd',
    mfgAddress: 'GIDC Estate, Phase II, Rajkot, Gujarat - 360003',
    countryOfOrigin: 'India',
    netQuantity: '100 g',
    mrp: '₹ 99.00 (incl. of all taxes)',
    unitSalePrice: '₹ 0.99 / g',
    mfgDate: '07/2026',
    expiryDate: '01/2027',
    batchNumber: 'BATCH-RC-GJ-420',
    consumerCare: 'care@royalcrunch.co.in',
    status: 'COMPLIANT',
    score: 92,
    lotSize: 850,
    samplesTested: 50,
    sampleSufficient: true,
    statutorySamplingNote: 'Rule requires testing a sample size of at least 50 packets before generating the legal report.',
    officerName: 'Insp. Sunita Banerjee',
    officerDesignation: 'Legal Metrology Inspector',
    inspectionLocation: 'Howrah Railway Retail Mart, Kolkata',
    storeName: 'Station Food Plaza',
    storeAddress: 'Howrah Junction, Kolkata - 711101',
    declarations: [],
    findings: [],
    images: [],
    remarks: 'Batch sample tested compliant with font size standards.',
    actionTaken: 'Passed Quality Verification',
  },
];
